### PR TITLE
[WIP] autocolorize model

### PR DESCRIPTION
**Pull request by kashif**
I am slowly converting the caffe autocolorize model to keras in the PR.

Some references:
- [caffe model viz](http://ethereon.github.io/netscope/#/gist/1ed728e7621d806ee594ba3f89b8fe29)
- [Project page and weights](http://people.cs.uchicago.edu/~larsson/colorization/)
- [Caffe model and code](https://github.com/gustavla/autocolorize)
- [Paper](http://arxiv.org/abs/1603.06668)

### CODE REVIEW

**Comment by fchollet** [comment]
I think it great, do you have any update on this? What's the status?

**Comment by kashif** [comment]
thanks @fchollet currently I am stuck at translating the `reshape` layer from caffe to keras. I also cannot read in the original layer into caffe, due to some dim mis-match... which making it hard for me to debug and check things...

I  would appreciate some help here, I was going to ask on gitter...

**Comment by fchollet** [comment]
Do post on Gitter, someone who is familiar with Caffe and Caffe conversion may be able to help out.

**Comment by fchollet** [comment]
@kashif please let me know when you think you are done.

**Comment by kashif** [comment]
@fchollet will do. Current issues with theano version:

- [ ] create weights from caffe weights 
- [ ] `TimeDistributed` deconvolution also needs a padding (only for GPU device)
- [ ] Figure out a "better" way of doing deconvolution with padding?
- [ ] A layer giving error:
     ```
ValueError: GpuReshape: cannot reshape input of shape (4096, 1, 2, 2) to shape (0, 4096, 120, 120).
Apply node that caused the error: GpuReshape{4}(GpuElemwise{Add}[(0, 0)].0, TensorConstant{[  -1 4096.. 120  120]})
Toposort index: 516
Inputs types: [CudaNdarrayType(float32, 4D), TensorType(int64, vector)]
Inputs shapes: [(4096, 1, 2, 2), (4,)]
Inputs strides: [(14400, 0, 120, 1), (8,)]
Inputs values: ['not shown', array([  -1, 4096,  120,  120])]
Outputs clients: [[GpuIncSubtensor{InplaceSet;::, ::, int64:int64:, int64:int64:}(GpuAlloc{memset_0=True}.0, GpuReshape{4}.0, Constant{4}, Constant{124}, Constant{4}, Constant{124})]]
     ```

TensorFlow version:

- [ ] recreate weights for TF
- [ ] test on TF

**Pull request closed without merging**
